### ISSUE TITLE
 I executed the test procedure and looked at the results, the amplitude of the voltage is satisfactory, but the error of the phase angle seems to be a bit large, do you know why

### ISSUE THREAD

**Issue by sajiaa** [jlara6/OpenPy-DSSE#1]
I'm trying to use this package, but I'm having the following issues while using it, please help me

 `F:\python3.9\Scripts\python.exe "F:\python project\test.py" 
OpenDSS Started successfully! 
OpenDSS Version 9.4.0.1 (64-bit build); License Status: Open 

State estimation of a single-phase distribution network 
F:\python3.9\lib\site-packages\openpy_dsse\YBus_Matrix_Pos_Seq.py:79: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  aux_i = (int(DF[DF['bus_name'] == from_bus]['bus_name_aux']) - 1)
F:\python3.9\lib\site-packages\openpy_dsse\YBus_Matrix_Pos_Seq.py:80: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  aux_j = (int(DF[DF['bus_name'] == to_bus]['bus_name_aux']) - 1)
Traceback (most recent call last):
  File "F:\python project\test.py", line 13, in <module>
    Results = dsse.estimate(
  File "F:\python3.9\lib\site-packages\openpy_dsse\state_estimation.py", line 148, in estimate
    V_Ang_EST = Sel_Alg.addresses_algorithm()
  File "F:\python3.9\lib\site-packages\openpy_dsse\Algorithm_classification.py", line 128, in addresses_algorithm
    state_estimation, MEAS_study = Alg_Typ.WLS_1ph_NV_Polar_linear_nonlinear_PMU(self.View_res)
  File "F:\python3.9\lib\site-packages\openpy_dsse\Algorithm_classification.py", line 198, in WLS_1ph_NV_Polar_linear_nonlinear_PMU
    df_MEAS_SCADA = get_MEAS.SCADA_MEAS()
  File "F:\python3.9\lib\site-packages\openpy_dsse\MEAS_from_OpenDSS.py", line 863, in SCADA_MEAS
    df_MEAS = df_MEAS.append(
  File "F:\python3.9\lib\site-packages\pandas\core\generic.py", line 5989, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'`

**Comment by sajiaa** [comment]
![Figure_1](https://user-images.githubusercontent.com/53387726/236615571-221fe0e2-d61e-426d-9227-dbc5a945ce0f.png)

**Comment by jlara6** [comment]
Thank you very much for testing OpenPy-DSSE, as found in the documentation it is a test example, the results depends on the type and location of the meters. You can try with another configuration of measurements following the instructions of the meters.

**Comment by sajiaa** [comment]
thank you ,sir
